### ISSUE TITLE
bug: Rename 改前改后uri被删除了一些信息

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#108]
Rename函数输入：
```
// oldURI: use://src/main/resources/mapper/QuestionExtMapper.xml[language=FILE]//mapper/update[parameterType=life.majiang.community.model.Question,language=XML,queryId=incCommentCount]//Update/Where/=/#{id}[language=SQL]
// newURI:
use://src/main/resources/mapper/QuestionExtMapper.xml[language=FILE]//mapper/update[parameterType=life.majiang.community.model.Question,language=XML,queryId=incCommentCount]//Update/Where/=/#{commentId}[language=SQL]
```
输出：
```
"def://src/main/java/life/majiang/community/model/Question.java[language=FILE]//Question/id[varType=Long,language=JAVA]" <-> def://life/majiang/community/model/Question.java[language=FILE]//Question/commentId[language=JAVA]
```
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/43695260/165262504-5fba7e7d-6214-43fe-9fec-381fe2a8d9d9.png">

**Comment by Shigma** [comment]
attr 缺失问题已经修复。

前半部分丢失问题希望能提供相关的配置（包括前置）。

**Comment by TsukimiRini** [comment]
> 前半部分丢失问题希望能提供相关的配置（包括前置）。
```yaml
r-paramType-identifier-update-no-jdbc:
    use:
      lang: XML
      file: (xmlFile).xml
      identifier: update
      queryId: (queryId)
      parameterType: (paramTypePackage:dot).(class)
      inline:
        identifier: "#{(name)}"
    def:
      lang: JAVA
      file: (paramTypePackage...)/(class).java
      identifier: (class)/(name)
```
单条，大概是file中的/问题，之前也讨论过
