### ISSUE TITLE
bug: auto capture rename没有按照识别得到的modifier模式

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#114]
```
// input
use://app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java[language=FILE]//DescriptionFragment/setupUploadDate/binding.detailUploadDateView[language=JAVA] <-> use://app/src/main/java/org/schabi/newpipe/fragments/detail/DescriptionFragment.java[language=FILE]//DescriptionFragment/setupUploadDate/binding.uploadDateView[language=JAVA]
// output
def://app/src/main/res/layout/fragment_description.xml[language=FILE]//androidx.core.widget.NestedScrollView/androidx.constraintlayout.widget.ConstraintLayout/TextView/android:id[language=XML]//@+id\\/detail_upload_date_view[language=ANY] <-> def://app/src/main/res/layout/fragment_description.xml[language=FILE]//androidx.core.widget.NestedScrollView/androidx.constraintlayout.widget.ConstraintLayout/TextView/android:id[language=XML]//@+id\\/uploadDateView[language=ANY]
```
使用的rule：
```yaml
# binding.widgetId <-> @+id/widgetId
  r-dataBinding:
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).(name:camel)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
```
