### ISSUE TITLE
bug: 可能是auto导致的rename过程中modifier会变化的问题

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#119]
目前rename中存在这样的错误例子（snake变成了camel）：
```
def://app/src/main/res/layout/item_everyday_three.xml[language=FILE]//layout/LinearLayout/LinearLayout/android:id[language=XML]//@+id\\/ll_three_one_three[language=ANY]
def://app/src/main/res/layout/item_everyday_three.xml[language=FILE]//layout/LinearLayout/LinearLayout/android:id[language=XML]//@+id\\/llThreeOneThird[language=ANY]
```
对应的是下面这条rule：
```yaml
r-dataBinding:
    use:
      lang: JAVA
      file: '(&javaFile).java'
      identifier: (&bindingVar).(name:camel)
    def:
      lang: XML
      file: (&layoutName).xml
      identifier: android:id
      inline:
        identifier: '@+id\/(name)'
```
对应的XLL为：
```
r-dataBinding
def://app/src/main/res/layout/item_everyday_three.xml[language=FILE]//layout/LinearLayout/LinearLayout/android:id[language=XML]//@+id\\/ll_three_one_three[language=ANY]
use://app/src/main/java/com/example/jingbin/cloudreader/adapter/EverydayAdapter.java[language=FILE]//EverydayAdapter/ThreeHolder/onBindingView/setOnClick/binding.llThreeOneThree[language=JAVA]
```
