### ISSUE TITLE
bug: project.rename返回的rename pair中部分oldURI实际并不存在

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#124]
遇到一个挺迷的bug，推测与auto有关

<img width="1576" alt="image" src="https://user-images.githubusercontent.com/43695260/169238174-72e2fc5c-aee7-4af9-89ad-a07fa4d05ced.png">

如上图，第一条用红框框出的uri实际并不存在于uriTree，它的真身应该是第二个红框内的uri。
输入的oldURI和newURI为：
```
def://app/src/main/res/layout/toolbar.xml[language=FILE]//LinearLayout/android.support.v7.widget.Toolbar/android:id[language=XML]//@+id\\/toolbar[language=ANY]
def://app/src/main/res/layout/toolbar.xml[language=FILE]//LinearLayout/android.support.v7.widget.Toolbar/android:id[language=XML]//@+id\\/tool_bar[language=ANY]
```
这种情况发生在我使用如下的rule时：
```yaml
r-id:
  use:
    lang: JAVA
    file: '(&javaFile).java'
    identifier: R.id.(name)
  def:
    lang: XML
    file: (&layoutName).xml
    identifier: android:id
    inline:
      identifier: '@+id\/(name)'
```
如果给name加上modifier就不会出现：
```yaml
r-id:
  use:
    lang: JAVA
    file: '(&javaFile).java'
    identifier: R.id.(name:snake)
  def:
    lang: XML
    file: (&layoutName).xml
    identifier: android:id
    inline:
      identifier: '@+id\/(name:snake)'
```
