### ISSUE TITLE
refactor：可能有必要调整 config 的格式

### ISSUE THREAD

**Issue by Shigma** [Symbolk/Code2Graph#40]
目前 rule 是一个数组：`[left, right, ...subrule]`。

但是随着 subrule 的开发，我发觉很多时候我们确实需要明确指定哪一个是 def 哪一个是 use，因此建议改成对象的写法。

```yaml
rules:
  - def:
      lang: Xml
      file: (layout).xml
    use:
      lang: Java
      file: '*.java'
      identifier: (layout)Binding
    subrules:
      - def:
          identifier: '@+id\/(name)'
        use:
          identifier: R.id.(name)
```
