### ISSUE TITLE
feat: attr的实现和支持

### ISSUE THREAD

**Issue by Symbolk** [Symbolk/Code2Graph#55]
为了支持类似Mybatis中的情况，需要加入对属性的支持，以增加匹配条件，减少误报

require：https://github.com/Symbolk/Code2Graph/issues/54

**Comment by TsukimiRini** [comment]
必须实现的attr：Mybatis中，XML文件里select、update等语句标签上的属性id，在FOCUS中以`select[id="queryID"]`形式出现。
之前讨论的是只在layer上加attr，但是实际上有占较大比重的情况需要用这样的rule解决：
```yaml
r-parameterType:
  use:
    lang: XML
    file: (*xmlFile).xml
    identifier: "select[id=(&queryId)]/parameterType"
    inline:
      identifier: (*paramTypePackage:dot)
  def:
    lang: JAVA
    file: (*paramTypePackage:slash).java
```
**讨论：** 可以考虑把id这个attr转化一下覆盖到标签下的部分子元素而不是只给语句标签本身，比如给像`parameterType`这样的标签属性也附加上比如`queryID`这样的attr。

**Comment by TsukimiRini** [comment]
@Shigma 可以描述下现在attr在config中的写法以及在构建uri时加attr的代码写法吗，可以直接贴例子

**Comment by Shigma** [comment]
构建 uri 添加 attr：

```java
layer.addAttribute(key, value)
```

配置语法：

```yaml
use:
    lang: XML
    file: (*xmlFile).xml
    identifier: "select/parameterType"
    queryId: xxx
    inline:
        identifier: (*paramTypePackage:dot)
```
