### ISSUE TITLE
dis: 一条use uri是否可以匹配多条def uri

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#97]
之前默认的行为是单条use只匹配多条def，按优先级匹配，一条use匹配到了def以后，优先级较低的rule就算也能为这条use匹配到def也不会被计入结果。
但是针对这个设计有一些反例。
情况1：由于动态因素等的介入，一个ref identifier本身就对应多个def
如在安卓项目中存在不同尺寸的layout文件，虽然组件组成相同（即文件内容）但放在不同路径下
<img width="545" alt="image" src="https://user-images.githubusercontent.com/43695260/162165225-9409ffc5-c978-4931-8475-701222b91a57.png">
但在java文件中对组件的引用并不会分开写，所以此处的引用标识符应当理解为有两处def：
<img width="774" alt="image" src="https://user-images.githubusercontent.com/43695260/162165442-96f5131c-7a9c-48f8-b67a-e02f67a77a2b.png">
不过这个例子在实际focus中并不会有问题，它会被判定为ambiguous，但最终输出依然会同时包含这两个link，因为它们同属于一条rule。我没能找到更适合的例子，所以编个假设情景：如果有例子里两个def对应的rule不同的话（比如，如果我写的rule更加精确，r-layout这条rule只匹配layout文件夹下的layout文件，另设一条rule只匹配layout-large-land下的layout文件），就会出现问题。

情况2：设想两条rule，存在两条link分别对应这两条rule并且use uri相同。为什么会存在这样的写法是因为两条rule匹配的重点不一样，一条rule匹配的是一个变量本身，另一条rule匹配的是这个变量对应的uri的其他要素，比如varType attribute。编个例子：
```yaml
r1:
  use:
    identifier: (class)/(name)
  def:
    identifier: (sqlTag)/#{(name)}
r2:
  use:
    identifier: (name)
    varType: (layout)Binding
  def:
    file: (layout).xml
```
不过这只是个纯设想的情景，贴上来只是起个参考作用，并没有实际例子，不用太在意

PS：这个问题只是拿出来讨论一下，优先级不高
