### ISSUE TITLE
bug: rule匹配可能有问题

### ISSUE THREAD

**Issue by TsukimiRini** [Symbolk/Code2Graph#98]
因为没有得到预想的效果，对mybatis项目的jeecg-boot项目的xll eva实验做了个测试。
我没有理解错的话，对于一个config文件的flowgraph，如果注释掉后半部分（即优先级较低的）rule在图中的声明，应该不会影响前半部分rule的匹配。比如：
```yaml
flowgraph:
  r-mapperBinding:
    - $
  r-queryId-select:
    - r-mapperBinding
  r-queryId-insert:
    - r-mapperBinding
  r-queryId-update:
    - r-mapperBinding
  r-queryId-delete:
    - r-mapperBinding
  r-paramAnno-select:
    - r-queryId-select
  r-paramAnno-insert:
    - r-queryId-insert
  r-paramAnno-update:
    - r-queryId-update
  r-paramAnno-delete:
    - r-queryId-delete
  # target rule
  r-paramAnno-select-no-jdbc:
    - r-queryId-select
  r-paramVarname-select:
    - r-queryId-select
  r-paramVarname-select-no-jdbc:
    - r-queryId-select
#  r-paramType-identifier-select:
#    - $
```
但事实上是在上面这个例子，注释掉r-paramType-identifier-select以后r-paramAnno-select-no-jdbc匹配到的结果相比没注释掉的多很多。（事实上，加了前者以后后者匹配到的条数为0）
为什么声明一个优先级低且没有前后置关系的rule会反而让优先级高的rule无法匹配呢？
